/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.computosas.vista;

import java.awt.HeadlessException;

/**
 *
 * @author Sebastian
 */
public class ClienteView extends javax.swing.JPanel {
    // Variable para capturar el ID del cliente seleccionado al hacer clic en la tabla
private int idClienteSeleccionado = -1;

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaClientesMouseClicked(evt);
    }
});

// Llamada inicial opcional para poblar la grilla al abrir la ventana
cargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirrecion", "Telefono", "Correo Electronico"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel1.setText("Nombre");

        jLabel2.setText("Dirreción");

        jLabel3.setText("Teléfono");

        jLabel4.setText("Correo");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        txtIdCliente.addActionListener(this::txtIdClienteActionPerformed);

        jLabel5.setText("ID");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(16, 16, 16)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
// 1. Conseguir la fila sobre la que el usuario hizo clic
    int filaSeleccionada = tablaClientes.getSelectedRow();
    
    // 2. Si la fila es válida (mayor o igual a 0) extraemos los datos
    if (filaSeleccionada >= 0) {
        // La columna 0 de tu JTable contiene el ID_CLIENTE
        String id = tablaClientes.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tablaClientes.getValueAt(filaSeleccionada, 1).toString();
        String direccion = tablaClientes.getValueAt(filaSeleccionada, 2).toString();
        String telefono = tablaClientes.getValueAt(filaSeleccionada, 3).toString();
        String correo = tablaClientes.getValueAt(filaSeleccionada, 4).toString();
        
        // 3. PASAR LOS DATOS A LOS COMPONENTES REALES
        txtIdCliente.setText(id); // <-- ¡Esto solucionará la carga del ID de una!
        txtNombre.setText(nombre);
        txtDireccion.setText(direccion);
        txtTelefono.setText(telefono);
        txtCorreo.setText(correo);
        
        // Deshabilitamos el campo del ID para que no lo editen por error al actualizar
        txtIdCliente.setEditable(false);
    }
    }

    /**
     * Consulta el listado completo mediante el DAO y actualiza el JTable en tiempo real.
     */
    public void cargarTablaClientes() {
        com.computosas.dao.ClienteDao dao = new com.computosas.dao.ClienteDao();
        java.util.List<com.computosas.modelo.Cliente> lista = dao.listarClientes();
        
        // Obtenemos el modelo estructural de la tabla de clientes
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        modelo.setRowCount(0); // Limpiamos la grilla para evitar duplicados visuales
        
        // Insertamos fila por fila con los datos provenientes de Neon Cloud
        for (com.computosas.modelo.Cliente c : lista) {
            Object[] fila = new Object[]{
                c.getIdCliente(),
                c.getNombre(),
                c.getDireccion(),
                c.getTelefono(),
                c.getCorreoElectronico()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * Vacía las cajas de texto y limpia la selección activa de la tabla.
     */
    private void limpiarFormulario() {
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        idClienteSeleccionado = -1; // Reseteamos la selección del ID
        tablaClientes.clearSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
// REEMPLAZAR LO QUE ESTÉ DENTRO DEL MÉTODO DEL BOTÓN REGISTRAR CON ESTO:
try {
    // 1. VALIDACIÓN: Verificar que los campos no estén vacíos en la interfaz
    if (txtIdCliente.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() ||
        txtDireccion.getText().trim().isEmpty() || txtTelefono.getText().trim().isEmpty() ||
        txtCorreo.getText().trim().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos de registro son obligatorios.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. CAPTURA DE DATOS DESDE LOS TEXTFIELDS
    int idCliente = Integer.parseInt(txtIdCliente.getText().trim());
    String nombre = txtNombre.getText().trim();
    String direccion = txtDireccion.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();

    // 3. CONSTRUIR INSTANCIA DEL MODELO CLIENTE
    com.computosas.modelo.Cliente nuevoCliente = new com.computosas.modelo.Cliente(idCliente, nombre, direccion, telefono, correo);
    com.computosas.dao.ClienteDao clienteDao = new com.computosas.dao.ClienteDao();

    // 4. PREVENCIÓN DE DUPLICADOS: Verificar si la cédula/NIT ya existe en Neon Cloud
    if (clienteDao.buscarClientePorId(idCliente) != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID/Cédula " + idCliente + " ya se encuentra registrado en el sistema.", "Registro Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. PERSISTENCIA: Invocar al DAO para insertar en PostgreSQL
    boolean exito = clienteDao.registrarCliente(nuevoCliente);

    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Cliente registrado exitosamente en CÓMPUTO S.A.S.!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // 6. LIMPIEZA AUTOMÁTICA DE CAMPOS
        txtIdCliente.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        
        // 7. RECARGAR LA TABLA VISUAL (Opcional: Si tienes un método para listar en JTable, llámalo aquí)
        // ejemplo: de_vuelta_a_cargar_tabla_clientes();
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error crítico: No se pudo conectar con el servidor para guardar el registro.", "Error de Almacenamiento", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "El campo de ID/Cédula debe ser un valor netamente numérico sin puntos ni letras.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (HeadlessException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Fallo inesperado en el módulo de control: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
if (idClienteSeleccionado == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona primero un cliente de la tabla para modificarlo.");
    return;
}

com.computosas.modelo.Cliente modificado = new com.computosas.modelo.Cliente(
    idClienteSeleccionado, 
    txtNombre.getText().trim(), 
    txtDireccion.getText().trim(), 
    txtTelefono.getText().trim(), 
    txtCorreo.getText().trim()
);

if (new com.computosas.dao.ClienteDao().actualizarCliente(modificado)) {
    javax.swing.JOptionPane.showMessageDialog(this, "¡El registro del cliente se actualizó correctamente!");
    cargarTablaClientes();
    limpiarFormulario();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
limpiarFormulario();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // 1. Validar si el usuario seleccionó una fila de la tabla
    int filaSeleccionada = tablaClientes.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, seleccione el cliente que desea eliminar de la tabla.", 
            "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Obtener el ID del cliente de la columna 0 (primera columna de tu tabla)
    int idCliente = Integer.parseInt(tablaClientes.getValueAt(filaSeleccionada, 0).toString());
    String nombreCliente = tablaClientes.getValueAt(filaSeleccionada, 1).toString();

    // 3. Ventana de confirmación (Buenas prácticas)
    int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Seguro que deseas eliminar permanentemente al cliente " + nombreCliente + "?", 
        "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
        // 4. Instanciar el DAO y ejecutar la eliminación
        com.computosas.dao.ClienteDao clienteDao = new com.computosas.dao.ClienteDao();
        boolean eliminado = clienteDao.eliminarCliente(idCliente);

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente de Neon Cloud.");
            
            // 5. Refrescar la tabla para que desaparezca el registro de inmediato
            // (Reemplaza 'listarClientesPantalla' por el nombre de tu método que recarga la tabla)
            cargarTablaClientes();
            
            // Opcional: Limpiar los campos de texto si el ID quedó escrito
            txtIdCliente.setText("");
            txtNombre.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: No se pudo eliminar el cliente de la base de datos.", 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
 
    com.computosas.vista.MainFrame menuPrincipal = new com.computosas.vista.MainFrame();
    menuPrincipal.setLocationRelativeTo(null); // Centra la ventana
    menuPrincipal.setVisible(true);            // La muestra en pantalla
    
    java.awt.Window ventanaContenedora = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (ventanaContenedora != null) {
        ventanaContenedora.dispose(); 
    }
    }//GEN-LAST:event_btnRegresarActionPerformed
public void cargarHistorialCompras(int idCliente, String nombreCliente) {
        try {
            // 1. Conectarse al VentaDAO y traer los datos correspondientes a este ID
            com.computosas.dao.VentaDAO ventaDao = new com.computosas.dao.VentaDAO();
            java.util.List<String[]> compras = ventaDao.obtenerHistorialPorCliente(idCliente);
            
            // 2. Si el cliente no registra compras, avisar cordialmente
            if (compras.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El cliente " + nombreCliente + " no registra transacciones comerciales previas.", "Historial Vacío", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // 3. Crear una JTable estructural de forma dinámica para renderizar el reporte técnico
            String[] cabecera = {"Folio de Factura", "Fecha de Compra", "Estatus de Venta", "Total (IVA Inc.)"};
            javax.swing.table.DefaultTableModel modeloReporte = new javax.swing.table.DefaultTableModel(cabecera, 0);
            
            for (String[] compra : compras) {
                modeloReporte.addRow(compra);
            }
            
            javax.swing.JTable tablaReporte = new javax.swing.JTable(modeloReporte);
            javax.swing.JScrollPane contenedor = new javax.swing.JScrollPane(tablaReporte);
            contenedor.setPreferredSize(new java.awt.Dimension(500, 200));
            
            // 4. Desplegar en pantalla como ventana de auditoría gerencial
            javax.swing.JOptionPane.showMessageDialog(this, contenedor, "Historial Indexado de Compras: " + nombreCliente, javax.swing.JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el historial indexado: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
