/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.computosas.vista;
import com.computosas.dao.ClienteDao;
import com.computosas.modelo.Cliente;
/**
 *
 * @author ASUS
 */
public class LoginClienteView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginClienteView.class.getName());

    /**
     * Creates new form LoginClienteView
     */
    public LoginClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(this::RegistrarseActionPerformed);

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(this::btnAdminActionPerformed);

        jLabel1.setText("Ingrese su ID:");

        jLabel2.setText("Ingrese su contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdmin)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContraseña)
                    .addComponent(txtUsuario)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdmin)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addGap(18, 18, 18)
                .addComponent(Registrarse)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
String idStr = txtUsuario.getText().trim(); // El campo donde meten el ID
    String password = new String(txtContraseña.getPassword()).trim();
    
    if (idStr.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        int idCliente = Integer.parseInt(idStr);
        
        ClienteDao clienteDao = new ClienteDao();
        if (clienteDao.validarLoginCliente(idCliente, password)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido al sistema!");
            
            // Abre la vista de ventas
            VentaView venta = new VentaView();
            venta.setLocationRelativeTo(null);
            venta.setVisible(true);
            
            this.dispose(); // Cierra el Login
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID de Cliente o Contraseña incorrectos.", "Error de Autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
// Creamos los componentes visuales para el formulario emergente
    javax.swing.JTextField txtId = new javax.swing.JTextField();
    javax.swing.JTextField txtNombre = new javax.swing.JTextField();
    javax.swing.JTextField txtDireccion = new javax.swing.JTextField();
    javax.swing.JTextField txtTelefono = new javax.swing.JTextField();
    javax.swing.JTextField txtCorreo = new javax.swing.JTextField();
    javax.swing.JPasswordField txtClave = new javax.swing.JPasswordField();

    Object[] formulario = {
        "Cédula / ID Único (Números):", txtId,
        "Nombre Completo:", txtNombre,
        "Dirección de Residencia:", txtDireccion,
        "Teléfono de Contacto:", txtTelefono,
        "Correo Electrónico:", txtCorreo,
        "Establezca su Contraseña:", txtClave
    };

    int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        formulario, 
        "Registro de Nuevo Cliente - Cómputo S.A.S.", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (opcion == javax.swing.JOptionPane.OK_OPTION) {
        // Validamos que ningún campo esté vacío
        String password = new String(txtClave.getPassword()).trim();
        if (txtId.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID, Nombre y Contraseña son obligatorios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Mapeamos los datos al objeto Cliente
            Cliente nuevoCliente = new Cliente();
            nuevoCliente.setIdCliente(Integer.parseInt(txtId.getText().trim()));
            nuevoCliente.setNombre(txtNombre.getText().trim());
            nuevoCliente.setDireccion(txtDireccion.getText().trim());
            nuevoCliente.setTelefono(txtTelefono.getText().trim());
            nuevoCliente.setCorreoElectronico(txtCorreo.getText().trim());
            nuevoCliente.setContrasena(password); // <-- Aquí se asigna la clave ingresada

            // Enviamos al DAO para persistir en Neon Cloud
            ClienteDao dao = new ClienteDao();
            if (dao.registrarCliente(nuevoCliente)) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Registro Exitoso! Ya puede iniciar sesión con su ID y contraseña.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el cliente. Posible ID duplicado.", "Error de Base de Datos", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser estrictamente numérico.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
       // Abre directamente el Login de Administrador
    LoginView loginAdmin = new LoginView();
    loginAdmin.setLocationRelativeTo(null); // Centra el login de admin
    loginAdmin.setVisible(true);            // Lo muestra en pantalla
    
    this.dispose(); // Cierra el login de clientes actual y libera memoria
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginClienteView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
