/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.computosas.vista;

/**
 *
 * @author ASUS
 */
public class VentaView extends javax.swing.JFrame {

    /**
     * Recalcula los montos económicos en pantalla leyendo la tabla del carrito.
     * Corregido para evitar errores de autounboxing (NullPointerException).
     */
    private void actualizarTotalesPantalla() {
        double subtotalAcumulado = 0;
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
        
        // Recorremos las filas de la tabla para sumar la columna del Subtotal (Índice 4)
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valorCelda = modelo.getValueAt(i, 4);
            // Validamos que la celda no esté vacía ni sea nula antes de convertirla
            if (valorCelda != null && !valorCelda.toString().trim().isEmpty()) {
                try {
                    subtotalAcumulado += Double.parseDouble(valorCelda.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error al convertir el subtotal en la fila " + i + ": " + e.getMessage());
                }
            }
        }
        
        double iva = subtotalAcumulado * 0.19; // IVA reglamentario del 19%
        double total = subtotalAcumulado + iva;
        
        // Seteamos los textos en tus componentes reales de la interfaz
        lblSubtotal.setText(String.format("$ %.2f", subtotalAcumulado));
        lblIva.setText(String.format("$ %.2f", iva));
        lblTotal.setText(String.format("$ %.2f", total));
    }

    // Lista que guardará todos los productos que traemos de la base de datos
    private java.util.List<com.computosas.modelo.Producto> listaTodosLosProductos = new java.util.ArrayList<>();

    // Lista temporal para los productos que el usuario va metiendo al carrito
    private java.util.List<com.computosas.modelo.Producto> listaTemporalProductos = new java.util.ArrayList<>();
    
    // Logger para registrar eventos o errores de la vista
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentaView.class.getName());

    /**
     * Trae los productos desde PostgreSQL (Neon Cloud) y los carga en el ComboBox.
     */
    private void cargarProductosEnCombo() {
        try {
            com.computosas.dao.ProductoDAO prodDAO = new com.computosas.dao.ProductoDAO();
            // Llamamos al método de tu DAO para listar productos
            listaTodosLosProductos = prodDAO.listarProductos(); 
            
            cmbProducto.removeAllItems();
            for (com.computosas.modelo.Producto p : listaTodosLosProductos) {
                cmbProducto.addItem(p.getNombre()); // Muestra el nombre en el combobox
            }
        } catch (Exception e) {
            System.out.println("Error al cargar productos: " + e.getMessage());
        }
        
    }

    /**
     * Constructor de la ventana VentaView.
     */
    public VentaView() {
        initComponents();
        cargarProductosEnCombo();
        actualizarTotalesPantalla();
        
    }

    // El resto de los métodos generados por NetBeans (initComponents, etc.) van aquí abajo...


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnFinalizarVenta = new javax.swing.JButton();
        btnAgregarCarrito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Cliente:");

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Productos:");

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio unitario", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaCarrito);

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta Débito", "Tarjeta Crédito" }));

        jLabel6.setText("Metodo de pago:");

        btnFinalizarVenta.setForeground(new java.awt.Color(255, 0, 0));
        btnFinalizarVenta.setText("Finalizar venta");
        btnFinalizarVenta.addActionListener(this::btnFinalizarVentaActionPerformed);

        btnAgregarCarrito.setForeground(new java.awt.Color(0, 255, 0));
        btnAgregarCarrito.setText("Añadir al carrito");
        btnAgregarCarrito.addActionListener(this::btnAgregarCarritoActionPerformed);

        jLabel3.setText("Subtotal:");

        jLabel4.setText("IVA (19%)");

        jLabel7.setText("Total");

        lblSubtotal.setText("Subtotal:");

        lblIva.setText("Subtotal:");

        lblTotal.setText("Subtotal:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIva, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAgregarCarrito)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblIva))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal))
                .addGap(68, 68, 68)
                .addComponent(btnFinalizarVenta)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        // TODO add your handling code here:
   try {
        Object prodSeleccionado = cmbProducto.getSelectedItem();
        if (prodSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
            return;
        }

        int idProducto = 0;
        String nombreProducto = "";
        double precioVenta = 0.0;

        String comboStr = prodSeleccionado.toString();
        for (com.computosas.modelo.Producto p : listaTodosLosProductos) {
            if (p.getNombre().equalsIgnoreCase(comboStr)) {
                idProducto = p.getIdProducto();
                nombreProducto = p.getNombre();
                precioVenta = p.getPrecioVenta();
                break;
            }
        }

        if (idProducto == 0) return;

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
        boolean existeEnTabla = false;
        int filaExistente = -1;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object cellId = modelo.getValueAt(i, 0);
            if (cellId != null && Integer.parseInt(cellId.toString()) == idProducto) {
                existeEnTabla = true;
                filaExistente = i;
                break;
            }
        }

        if (existeEnTabla) {
            Object cantObj = modelo.getValueAt(filaExistente, 2);
            int cantidadActual = (cantObj != null) ? Integer.parseInt(cantObj.toString()) : 0;
            int nuevaCantidad = cantidadActual + 1;
            double nuevoSubtotal = nuevaCantidad * precioVenta;

            modelo.setValueAt(nuevaCantidad, filaExistente, 2);
            modelo.setValueAt(nuevoSubtotal, filaExistente, 4);
        } else {
            Object[] nuevaFila = new Object[5];
            nuevaFila[0] = idProducto;
            nuevaFila[1] = nombreProducto;
            nuevaFila[2] = 1;
            nuevaFila[3] = precioVenta;
            nuevaFila[4] = precioVenta;

            // Agrega de forma ordenada al final de la tabla
            modelo.addRow(nuevaFila);
        }

        actualizarTotalesPantalla();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al añadir: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
try {
    // 1. VALIDACIÓN DEL CLIENTE
    String idClienteStr = txtIdCliente.getText().trim();
    if (idClienteStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID del cliente para la facturación.", "Falta Información", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    int idCliente = Integer.parseInt(idClienteStr);

    com.computosas.dao.ClienteDao clienteDAO = new com.computosas.dao.ClienteDao();
    com.computosas.modelo.Cliente clienteReal = clienteDAO.buscarClientePorId(idCliente);
    String nombreCliente = (clienteReal != null) ? clienteReal.getNombre() : "Cliente General";
    String correoCliente = (clienteReal != null) ? clienteReal.getCorreoElectronico() : "N/A";
    String telefonoCliente = (clienteReal != null) ? clienteReal.getTelefono() : "N/A";

    // 2. LEER TABLA DEL CARRITO
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
    listaTemporalProductos.clear();
    
    com.computosas.dao.ProductoDAO productoDAO = new com.computosas.dao.ProductoDAO();
    
    // Banderas de control de stock y alarmas
    boolean requiereImportacion = false;
    StringBuilder alarmasStockText = new StringBuilder();
    StringBuilder reporteImportaciones = new StringBuilder();
    int conteoTotalPiezas = 0; 

    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        Object idObj = modeloTabla.getValueAt(i, 0);
        Object cantObj = modeloTabla.getValueAt(i, 2);
        if (idObj == null || cantObj == null) continue;
        
        int idProd = Integer.parseInt(idObj.toString().trim());
        int cantidadSolicitada = Integer.parseInt(cantObj.toString().trim());
        conteoTotalPiezas += cantidadSolicitada;
        
        // Buscar el objeto Producto original
        com.computosas.modelo.Producto prodOriginal = null;
        for (com.computosas.modelo.Producto p : listaTodosLosProductos) {
            if (p.getIdProducto() == idProd) {
                prodOriginal = p;
                break;
            }
        }

        if (prodOriginal != null) {
            // CONSULTA DE STOCK REAL EN BD (Captura segura de no soportado)
            int stockEnBodega = 0;
            try {
                stockEnBodega = productoDAO.obtenerStockActual(idProd);
            } catch (UnsupportedOperationException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Aviso: El método 'obtenerStockActual' en ProductoDAO no está implementado aún.", "Verificar ProductoDAO", javax.swing.JOptionPane.WARNING_MESSAGE);
                stockEnBodega = 10; // Stock ficticio de emergencia para no trabar la venta
            }
            
            if (stockEnBodega <= 0) {
                requiereImportacion = true;
                alarmasStockText.append("🚨 [ALERTA DE DESABASTECIMIENTO] El producto: '")
                               .append(prodOriginal.getNombre())
                               .append("' tiene 0 unidades en bodega. Se registrará BAJO PEDIDO.\n");
                
                int diasEstimados = (int)(Math.random() * 6) + 5; 
                reporteImportaciones.append("• ").append(prodOriginal.getNombre())
                                    .append(" -> Tiempo estimado de arribo aduanero: ")
                                    .append(diasEstimados).append(" días hábiles.\n");
                                    
            } else if (stockEnBodega - cantidadSolicitada <= 2) {
                int remanente = stockEnBodega - cantidadSolicitada;
                if (remanente <= 0) {
                    alarmasStockText.append("⚠️ [ALERTA CRÍTICA] El producto: '")
                                   .append(prodOriginal.getNombre())
                                   .append("' SE AGOTARÁ POR COMPLETO tras esta transacción.\n");
                } else {
                    alarmasStockText.append("⚡ [ALERTA DE STOCK MÍNIMO] El producto: '")
                                   .append(prodOriginal.getNombre())
                                   .append("' quedará con inventario bajo de seguridad (")
                                   .append(remanente).append(" unds).\n");
                }
            }

            for (int c = 0; c < cantidadSolicitada; c++) {
                listaTemporalProductos.add(prodOriginal);
            }
        }
    }

    if (listaTemporalProductos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El carrito de compras está vacío.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (alarmasStockText.length() > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, alarmasStockText.toString(), "SISTEMA DE CONTROL DE INVENTARIOS BODEGA", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    // 3. CONFIGURAR EL OBJETO VENTA
    com.computosas.modelo.Venta nuevaVenta = new com.computosas.modelo.Venta();
    int folioAleatorio = (int)(Math.random() * 90000) + 10000; 
    nuevaVenta.setFolio(String.valueOf(folioAleatorio));
    
    // FORMATO DE FECHA PARA BASE DE DATOS (Nativo PostgreSQL: yyyy-MM-dd)
    java.text.SimpleDateFormat sdfFecha = new java.text.SimpleDateFormat("yyyy-MM-dd");
    java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("HH:mm:ss");
    java.util.Date fechaData = new java.util.Date();
    
    nuevaVenta.setFechaVenta(sdfFecha.format(fechaData));
    nuevaVenta.setHoraVenta(sdfHora.format(fechaData));
    nuevaVenta.setIdCliente(idCliente);
    
    if (requiereImportacion) {
        nuevaVenta.setEstatusVenta("PENDIENTE");
    } else {
        nuevaVenta.setEstatusVenta("ENTREGADA");
    }

    // Parseo ultra-seguro de los precios de pantalla
    String subtotalStr = lblSubtotal.getText().replaceAll("[\\$\\s,]", "").replace(".00", "").trim();
    String totalStr = lblTotal.getText().replaceAll("[\\$\\s,]", "").replace(".00", "").trim();
    
    double subtotalLimpio = subtotalStr.isEmpty() ? 0.0 : Double.parseDouble(subtotalStr);
    double totalLimpio = totalStr.isEmpty() ? 0.0 : Double.parseDouble(totalStr);
    
    nuevaVenta.setSubtotalSinIVA(subtotalLimpio);
    nuevaVenta.setTotalConIVA(totalLimpio);

    for (com.computosas.modelo.Producto prod : listaTemporalProductos) {
        nuevaVenta.agregarProducto(prod);
    }

    // 4. GUARDAR EN LA BASE DE DATOS
    com.computosas.dao.VentaDAO ventaDAO = new com.computosas.dao.VentaDAO();
    boolean exitoBD = ventaDAO.registrarVenta(nuevaVenta);
    
    if (!exitoBD) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Operación cancelada por fallo en el Servidor de Datos. Revisa las columnas en Neon.", "Error BD", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. DESCONTAR STOCK REAL
    for (com.computosas.modelo.Producto prod : listaTemporalProductos) {
        try {
            int stockActual = productoDAO.obtenerStockActual(prod.getIdProducto());
            if (stockActual > 0) {
                productoDAO.restarStock(prod.getIdProducto(), 1);
            }
        } catch (UnsupportedOperationException ex) {
            // Bloque silencioso para que no tumbe la generación de la factura si restarStock no está listo
        }
    }

    // 6. GENERACIÓN EXHAUSTIVA DE DOCUMENTACIÓN CORPORATIVA
    StringBuilder reporteCompleto = new StringBuilder();
    String metodoPago = (cmbMetodoPago.getSelectedItem() != null) ? cmbMetodoPago.getSelectedItem().toString() : "Efectivo";

    // =========================================================================
    // DOCUMENTO I: COMPROBANTE DE VENTA (FACTURA ORIGINAL)
    // =========================================================================
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("        DOCUMENTO I: COMPROBANTE DE VENTA (FACTURA)\n");
    reporteCompleto.append("                  CÓMPUTO S.A.S.                  \n");
    reporteCompleto.append("               NIT: 901.452.871 - 4                 \n");
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("Folio Factura: ").append(nuevaVenta.getFolio()).append("\n");
    reporteCompleto.append("Fecha Emisión: ").append(nuevaVenta.getFechaVenta()).append(" | ").append(nuevaVenta.getHoraVenta()).append("\n");
    reporteCompleto.append("Estatus Orden: ").append(nuevaVenta.getEstatusVenta()).append("\n");
    reporteCompleto.append("Método Pago:   ").append(metodoPago).append("\n");
    reporteCompleto.append("--------------------------------------------------\n");
    reporteCompleto.append("DATOS DEL CLIENTE:\n");
    reporteCompleto.append(" Identificación: ").append(idCliente).append("\n");
    reporteCompleto.append(" Nombre:         ").append(nombreCliente).append("\n");
    reporteCompleto.append(" Correo/Tel:     ").append(correoCliente).append(" / ").append(telefonoCliente).append("\n");
    reporteCompleto.append("--------------------------------------------------\n");
    reporteCompleto.append(String.format("%-25s %-5s %-10s %-10s\n", "Producto", "Cant", "Precio U.", "Subtotal"));
    reporteCompleto.append("--------------------------------------------------\n");
    
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        Object nomObj = modeloTabla.getValueAt(i, 1);
        Object cantObj = modeloTabla.getValueAt(i, 2);
        Object precObj = modeloTabla.getValueAt(i, 3);
        Object subtObj = modeloTabla.getValueAt(i, 4);
        if (nomObj == null || cantObj == null || precObj == null || subtObj == null) continue;
        
        String prodNom = nomObj.toString();
        int cant = Integer.parseInt(cantObj.toString().trim());
        double prec = Double.parseDouble(precObj.toString().replaceAll("[\\$\\s,]", ""));
        double subt = Double.parseDouble(subtObj.toString().replaceAll("[\\$\\s,]", ""));
        
        if (prodNom.length() > 24) prodNom = prodNom.substring(0, 21) + "...";
        reporteCompleto.append(String.format("%-25s %-5d $%-9.2f $%-9.2f\n", prodNom, cant, prec, subt));
    }
    
    reporteCompleto.append("--------------------------------------------------\n");
    reporteCompleto.append(" Total Ítems / Piezas: ").append(conteoTotalPiezas).append(" unidades\n");
    reporteCompleto.append(" Base Gravable (Subtotal): ").append(lblSubtotal.getText()).append("\n");
    reporteCompleto.append(" Impuesto Liquidado (IVA 19%): ").append(lblIva.getText()).append("\n");
    reporteCompleto.append(" TOTAL FACTURADO COMPRA:       ").append(lblTotal.getText()).append("\n");
    
    if (requiereImportacion) {
        reporteCompleto.append("--------------------------------------------------\n");
        reporteCompleto.append("⚠️ LOGÍSTICA DE IMPORTACIONES APLICADA:\n");
        reporteCompleto.append(reporteImportaciones.toString());
    }
    reporteCompleto.append("==================================================\n\n\n");

    // =========================================================================
    // DOCUMENTO II: PÓLIZA DE GARANTÍA LEGAL Y TÉCNICA
    // =========================================================================
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("        DOCUMENTO II: PÓLIZA DE GARANTÍA LEGAL      \n");
    reporteCompleto.append("                  CÓMPUTO S.A.S.                  \n");
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("Folio Comercial: ").append(nuevaVenta.getFolio()).append("\n");
    reporteCompleto.append("Fecha de Corte:  ").append(nuevaVenta.getFechaVenta()).append(" - ").append(nuevaVenta.getHoraVenta()).append("\n");
    reporteCompleto.append("Comprador Titular: ").append(nombreCliente).append(" (CC: ").append(idCliente).append(")\n");
    reporteCompleto.append("--------------------------------------------------\n");
    reporteCompleto.append("IDENTIFICACIÓN INEQUÍVOCA DE COMPONENTES DISPUESTOS:\n");
    reporteCompleto.append("--------------------------------------------------\n");
    
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        Object idObj = modeloTabla.getValueAt(i, 0);
        Object cantObj = modeloTabla.getValueAt(i, 2);
        if (idObj == null || cantObj == null) continue;
        
        int idProd = Integer.parseInt(idObj.toString().trim());
        int cant = Integer.parseInt(cantObj.toString().trim());
        
        com.computosas.modelo.Producto pRef = null;
        for (com.computosas.modelo.Producto p : listaTodosLosProductos) {
            if (p.getIdProducto() == idProd) { 
                pRef = p; 
                break; 
            }
        }
        
        if (pRef != null) {
            String serial = "N/A - COMPONENTE ESTÁNDAR";
            int diasGarantia = 180; 
            
            if (pRef instanceof com.computosas.modelo.Teclado) {
                com.computosas.modelo.Teclado tec = (com.computosas.modelo.Teclado) pRef;
                serial = (tec.getNumeroSerie() != null) ? tec.getNumeroSerie() : "SN-TEC-" + folioAleatorio + "-" + i;
                diasGarantia = tec.getDuracionGarantiaDias();
            } else if (pRef instanceof com.computosas.modelo.Monitor) {
                serial = "SN-MON-" + folioAleatorio + "-" + i; 
                diasGarantia = 365; 
            }
            
            reporteCompleto.append("• Ítem: ").append(pRef.getNombre()).append(" [Cant: ").append(cant).append("]\n");
            reporteCompleto.append("  Número de Serie (S/N): ").append(serial).append("\n");
            reporteCompleto.append("  Cobertura Técnica Obligatoria: ").append(diasGarantia).append(" días calendario.\n\n");
        }
    }
    reporteCompleto.append("Condiciones: La cobertura aplica únicamente por fallas técnicas de fábrica.\n");
    reporteCompleto.append("==================================================\n\n\n");

    // =========================================================================
    // DOCUMENTO III: MANIFIESTO DE IMPORTACIÓN ADUANERO
    // =========================================================================
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("     DOCUMENTO III: MANIFIESTO DE IMPORTACIÓN ADUANERA\n");
    reporteCompleto.append("        DECLARACIÓN ADUANERA DE MERCANCÍAS (DIAN)  \n");
    reporteCompleto.append("==================================================\n");
    reporteCompleto.append("Importador Responsable: CÓMPUTO S.A.S.\n");
    reporteCompleto.append("Fecha de Procesamiento: ").append(nuevaVenta.getFechaVenta()).append("\n");
    reporteCompleto.append("Folio Comercial Asociado: ").append(nuevaVenta.getFolio()).append("\n");
    reporteCompleto.append("Destinatario Final/Adquiriente: ").append(nombreCliente).append("\n");
    reporteCompleto.append("--------------------------------------------------\n");
    reporteCompleto.append("CARACTERIZACIÓN FÍSICO-GEOGRÁFICA DE LOS DISPOSITIVOS:\n");
    reporteCompleto.append("--------------------------------------------------\n");
    
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        Object idObj = modeloTabla.getValueAt(i, 0);
        if (idObj == null) continue;
        int idProd = Integer.parseInt(idObj.toString().trim());
        
        com.computosas.modelo.Producto pRef = null;
        for (com.computosas.modelo.Producto p : listaTodosLosProductos) {
            if (p.getIdProducto() == idProd) { 
                pRef = p; 
                break; 
            }
        }
        
        if (pRef != null) {
            String paisOrigen = "China (R.P.C.)"; 
            String dimensiones = "N/A - Empaque Estándar";
            String fabricante = "Componente OEM";
            int masaGramos = 450; 

            if (pRef instanceof com.computosas.modelo.Monitor) {
                com.computosas.modelo.Monitor mon = (com.computosas.modelo.Monitor) pRef;
                paisOrigen = mon.getPaisProcedencia();
                dimensiones = mon.getMedidas();
                fabricante = "Cómputo S.A.S. Global Division";
                masaGramos = 3800; 
            } else if (pRef instanceof com.computosas.modelo.Teclado) {
                fabricante = "Logitech / Genius Certificado";
                dimensiones = "45cm x 15cm x 3cm";
                masaGramos = 750;
            }
            
            reporteCompleto.append("• Dispositivo: ").append(pRef.getNombre()).append("\n");
            reporteCompleto.append("  Fabricante/Marca: ").append(fabricante).append("\n");
            reporteCompleto.append("  País de Procedencia/Origen: ").append(paisOrigen).append("\n");
            reporteCompleto.append("  Masa Métrica Estimada: ").append(masaGramos).append(" gramos.\n");
            reporteCompleto.append("  Dimensiones Dimensionales: ").append(dimensiones).append("\n\n");
        }
    }
    reporteCompleto.append("Manifiesto legalizado bajo el régimen de importación de tecnología libre.\n");
    reporteCompleto.append("==================================================\n");

    // 7. DESPLEGAR REPORTES COMPLETOS
    javax.swing.JTextArea txtAreaDocumento = new javax.swing.JTextArea(25, 65);
    txtAreaDocumento.setText(reporteCompleto.toString());
    txtAreaDocumento.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12)); 
    txtAreaDocumento.setEditable(false); 

    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(txtAreaDocumento);
    javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Transacción Procesada - Folio: " + nuevaVenta.getFolio(), javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // 8. RESETEAR PANTALLA
    modeloTabla.setRowCount(0); 
    txtIdCliente.setText("");   
    this.actualizarTotalesPantalla(); 

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Fallo detectado en la lógica del formulario: " + e.getMessage(), "Error de Ejecución", javax.swing.JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}
    
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        // Preguntamos para asegurar que de verdad quiere salir
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro que desea cerrar sesión y regresar al inicio?", 
        "Cerrar Sesión", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // Creamos y centramos la ventana del login de clientes
        com.computosas.vista.LoginClienteView loginCliente = new com.computosas.vista.LoginClienteView();
        loginCliente.setLocationRelativeTo(null); 
        loginCliente.setVisible(true);
        
        // Destruimos la ventana de ventas actual
        this.dispose(); 
    }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentaView().setVisible(true));
    }
    /**
 * FACTURACIÓN: Calcula de forma automática la matriz de impuestos de la venta actual
 * basándose en los productos acumulados en la JTable de la cesta de compras.
 */
public void calcularTotalesFactura() {
    try {
        
    
        javax.swing.table.DefaultTableModel modeloCesta = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
        double subtotalSinIVA = 0.0;
        
      
        for (int i = 0; i < modeloCesta.getRowCount(); i++) {
            double precio = Double.parseDouble(modeloCesta.getValueAt(i, 3).toString());
            int cantidad = Integer.parseInt(modeloCesta.getValueAt(i, 4).toString());
            
            subtotalSinIVA += (precio * cantidad);
        }
        
       
        double impuestoIVA = subtotalSinIVA * 0.19; // IVA del 19%
        double totalConIVA = subtotalSinIVA + impuestoIVA;
        
        
        
        
    } catch (Exception e) {
        System.err.println("Error en el cálculo automático de totales: " + e.getMessage());
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTextField txtIdCliente;
    // End of variables declaration//GEN-END:variables
}
